secretsegypt3-main/Post/urls.py
from django.conf.urls import url
from . import views


app_name = 'Post'


urlpatterns  = [
    url( r'^$' , views.index , name='index'),
    url( 'baset' , views.baset , name='baset'),
    url('all_posts' , views.all_posts , name='all_posts'),
    url(r'^(?P<id>\d+)$', views.post , name='post'),
    url('create',views.create_post, name='create_post'),
    url(r'^(?P<id>\d+)/edit$', views.edit_post ,name='edit_post'),
    url('<slug:slug>/', views.post_detail, name='post_detail')




]

secretsegypt3-main/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),
    path('property', include('property.urls',namespace='property' )),
    path('aswan', include('aswan.urls',namespace='aswan' )),
    path('cairotour', include('cairotour.urls',namespace='cairotour' )),
    path('nilecruise', include('nilecruise.urls',namespace='nilecruise' )),
    path('makeatrip', include('makeatrip.urls',namespace='makeatrip' )),
    path('packages', include('packages.urls',namespace='packages' )),
    path('luxortour', include('luxortour.urls',namespace='luxortour' )),
    path('about', include('about.urls',namespace='about' )),
    path('', include('Post.urls',namespace='project' )),
    path('contact-us/', include('contact.urls',namespace='contact')),
    path('summernote/', include('django_summernote.urls')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_title = "Inspiringegypttours "
admin.site.site_header = "Inspiringegypttours "
admin.site.index_title = "Inspiringegypttours  "
admin.site.accounts = "Inspiringegypttours  "
admin.site.profile = "Inspiringegypttours  "

secretsegypt3-main/Post/models.py
from django.db import models
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.utils.text import slugify
from ckeditor.fields import RichTextField
from taggit.managers import TaggableManager
from django.utils.translation import gettext as _
# Create your models here.
#3   user-title-content-image-created
class Post (models.Model):

    user = models.ForeignKey(User , on_delete=models.CASCADE)
    tags = TaggableManager()
    title = models.CharField(max_length=50)
    content = RichTextField()
    category = models.ForeignKey('category', related_name='Post_category', on_delete=models.CASCADE)
    image = models.ImageField(upload_to="main_product"  ,blank=True, null=True)
    image1 = models.ImageField(upload_to="main_product", blank=True, null=True)
    image2 = models.ImageField(upload_to="main_product" , blank=True, null=True)
    created = models.DateTimeField(default=timezone.now)
    active  = models.BooleanField(default=True)

    def __str__(self):
       return self.title

class category(models.Model):
    category = models.CharField(max_length=40)
    def __str__(self):
        return self.category

class slideImages(models.Model):

  user = models.ForeignKey(User , on_delete=models.CASCADE)
  image1 = models.ImageField(upload_to="main_product"  ,blank=True, null=True)
  image2 = models.ImageField(upload_to="main_product", blank=True, null=True)
  image3 = models.ImageField(upload_to="main_product", blank=True, null=True)
  image4 = models.ImageField(upload_to="main_product", blank=True, null=True)
  created = models.DateTimeField(default=timezone.now)
  active  = models.BooleanField(default=True)




class Comment(models.Model):
    name = models.CharField(max_length=80)
    image = models.ImageField(upload_to="main_product"  ,blank=True, null=True)
    email = models.EmailField()
    body = models.TextField(_("Comment :"),max_length=100)
    created_on = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return 'Comment {} by {}'.format(self.body, self.name)

secretsegypt3-main/Post/forms.py
from django import forms
from .models import Post,Comment
from ckeditor.widgets import CKEditorWidget
from ckeditor.widgets import CKEditorWidget

class PostForm(forms.ModelForm):
    content = forms.CharField(widget=CKEditorWidget())
    class Meta:
        model= Post
        fields = ['title' , 'content' , 'image' ,'image1' , 'image2']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body','image')

secretsegypt3-main/Post/templates/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404 ,redirect
from django.views.generic.edit import FormMixin

from django.views.generic import  ListView

from .models import about
from .models import gallery
# Create your views here.


class aboutList(ListView):
    model=about
    ##filer



def gallery_List(request):
    gallery_List = gallery.objects.all()

    page_number = request.GET.get('page')

    context = {'gallery_List' :gallery_List }

    return render(request ,  'gallery_List.html',context)

secretsegypt3-main/Post/views.py
from django.shortcuts import render, get_object_or_404 ,redirect
from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404 ,redirect
from django.views.generic.edit import FormMixin
from django.contrib.auth.models import User
from .forms import CommentForm


from django.views.generic import  ListView ,DetailView

# Create your views here.
from django import forms
from .models import Post
from .forms  import PostForm
from django.conf.urls import url
from django.core.paginator import Paginator
from property.models import property ,place
from aswan .models import aswan
from luxortour .models import luxortour
from cairotour  .models import cairotour
from  nilecruise  .models import  nilecruise
from  contact  .models import  Info
from  packages  .models import  packages
from django.http import HttpResponse
from .models import slideImages
from .models import Comment
from .forms import CommentForm

def error_404_view(request, exception):
    data = {"name": "ThePythonDjango.com"}
    return render(request,'404.html', data)



def index(request):


    Propertyrft = Post.objects.all()
    Propertyryt = luxortour.objects.all()[:3]
    aswanss = aswan.objects.all()[:3]
    cairoo = cairotour.objects.all()[:4]
    packagess = packages.objects.all()[:3]
    Infoo = Info.objects.all()[:1]
    Nilecruisee = nilecruise.objects.all()[:3]
    Infoo = Info.objects.all()
    Propertyrytt = property.objects.all()[:3]


    comments = Comment.objects.filter(active=True)[:2]

    slideImagess = slideImages.objects.all()[:1]

    if request.method== 'POST':

         comment_form = CommentForm(request.POST , request.FILES)
         if comment_form.is_valid():
            comment_form = comment_form.save(commit=False)
            comment_form.user = request.user
            comment_form.save()
            return redirect('/')


    else:
          comment_form = CommentForm()



    return render(request ,  'index.html',{

       'Propertyrft' : Propertyrft,
       'Propertyryt' : Propertyryt,
       'aswanss' : aswanss,
       'cairoo' : cairoo,
       'Nilecruisee' : Nilecruisee,
       'packagess' : packagess,
       'Infoo' : Infoo,
      'slideImagess' : slideImagess,
      'comments' : comments,
     'comment_form': comment_form,
      'Propertyrytt': Propertyrytt
    })



def baset(request):
    all_posts = Post.objects.filter(active=True)
    Infooo = Info.objects.all()


    return render(request ,  'baset.html',{

       'Infooo' : Infooo,

    })


def all_posts(request):
    all_posts = Post.objects.all()

    paginator = Paginator(all_posts, 5) # Show 25 contacts per page.
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {'all_posts' :page_obj }

    return render(request ,  'all_posts.html',context)



def post(request,  id):
    #post= Post.objects.get(id=id)
    post = get_object_or_404( Post , id=id)

    context = {
         'post' : post ,
    }
    return render(request , 'datail.html',context)


def create_post(request):
    if request.method== 'POST':

        form = PostForm(request.POST , request.FILES)
        if form.is_valid():
           new_form = form.save(commit=False)
           new_form.user = request.user
           new_form.save()
           return redirect('/')


    else:
         form = PostForm()

    context = {
        'form' : form ,
         }
    return render(request,'create.html',context)

def edit_post(request,  id):
    post = get_object_or_404( Post ,  id=id)
    if request.method== 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            new_form = form.save(commit=False)
            new_form.user = request.user
            new_form.save()
            return redirect('/')


    else:
         form = PostForm(instance=post)

    context = {
        'form' : form ,
  }
    return render(request,'edit.html',context)

def post_detail(request, slug):
    template_name = 'post_detail.html'
    post = get_object_or_404(Post, slug=slug)
    comments = post.comments.filter(active=True)
    new_comment = None
    # Comment posted
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():

            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()

    return render(request, Comment, {'post': post,
                                           'comments': comments,
                                           'new_comment': new_comment,
                                           'comment_form': comment_form})

secretsegypt3-main/Post/templates/Comment.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block body %}

 <form method = "Post" enctype="multipart/form-data">
   {% csrf_token %}
   {{ form.media }}
   {% bootstrap_form form %}
   {% buttons %}
         <button type="submit" class="btn btn-primary">Save post</button>
    {% endbuttons %}
 </form>
 {% endblock body%}

secretsegypt3-main/Post/templates/all_posts.html
{% extends "base.html" %}
{% block body %}


<!-- Breadcrumb Area Start -->
<section class="peulis-breadcrumb-area">
  <div class="breadcrumb-top">
    <div class="container">
      <div class="col-lg-12">
        <div class="breadcrumb-box">
          <h2>Blog With Sidebar</h2>
          <ul class="breadcrumb-inn">
            <li><a href="{% url 'project:index'%}">Home</a></li>
            <li class="active"><a href="{% url 'project:index'%}">Blog</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Breadcrumb Area End -->


<!-- Blog Area Start -->
<section class="peulis-blog-page-area section_70">
  <div class="container">
    <div class="row">
      <div class="col-lg-8">
        <div class="blog-page-left">
          <div class="single-blog-item">
            {% for post in all_posts %}
            <div class="blog-image">
              <a href="{% url 'project:post' post.id %}">
                {% if post.image %}
                <img src="{{post.image.url}}" alt="blog" />

                {% endif %}
              </a>
            </div>
            <div class="blog-desc">
              <div class="post-meta">
                <p class="date">{{post.created}}</p>
                <p>By <a href="#">Admin</a></p>
                <p><a href="#">3 comments</a></p>
              </div>
              <h3><a href="{% url 'project:post' post.id %}">{{post}}</a></h3>
              <p>{{post.content|safe|truncatewords:30}}</p>                alteration...</p>
              {% endfor %}
            </div>
          </div>
           </div>

          <!-- Pagination Start -->
          <div class="pagination-box-row">
            <ul class="pagination">
              <li class="active"><a href="#">1</a></li>
              <li><a href="#">2</a></li>
              <li><a href="#">3</a></li>
              <li><a href="#"><i class="fa fa-angle-double-right"></i></a></li>
            </ul>
          </div>
          <!-- Pagination End -->

        </div>
      </div>
      <div class="col-lg-4">
        <div class="sidebar-widget">
          <div class="single-sidebar">
            <form>
              <input type="search" placeholder="Search..." />
              <button type="submit"><i class="fa fa-search"></i></button>
            </form>
          </div>
          <div class="single-sidebar">
            <h3>Categories</h3>
            <ul class="category">
              <li><a href="#">Best Package</a></li>
              <li><a href="#">Destinations</a></li>
              <li><a href="#">Discovery</a></li>
              <li><a href="#">Travel</a></li>
              <li><a href="#">Trendy</a></li>
              <li><a href="#">Popular</a></li>
              <li><a href="#">Events</a></li>
            </ul>
          </div>
          <div class="single-sidebar">
            <h3>Tags</h3>
            <ul class="Tags-catagory">
              <li><a href="#">Fashion</a></li>
              <li><a href="#">Sea</a></li>
              <li><a href="#">Mountain</a></li>
              <li><a href="#">Enjoy</a></li>
              <li><a href="#">Hot</a></li>
              <li><a href="#">Popular</a></li>
              <li><a href="#">Events</a></li>
            </ul>
          </div>



          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Blog Area End -->
{% endblock body%}

secretsegypt3-main/Post/templates/create.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block body %}

 <form method = "Post" enctype="multipart/form-data">
   {% csrf_token %}
   {{ form.media }}
   {% bootstrap_form form %}
   {% buttons %}
         <button type="submit" class="btn btn-primary">Save post</button>
    {% endbuttons %}
 </form>
 {% endblock body%}

secretsegypt3-main/Post/templates/datail.html
{% extends "base.html" %}
{% block body %}
<!-- Breadcrumb Area Start -->
<section class="peulis-breadcrumb-area">
   <div class="breadcrumb-top">
      <div class="container">
         <div class="col-lg-12">
            <div class="breadcrumb-box">
               <h2>Blog Details</h2>
                <ul class="breadcrumb-inn">
                  <li><a href="{% url 'project:index'%}">Home</a></li>
                  <li class="active"><a href="{% url 'project:index'%}">Blog Details</a></li>
                </ul>
            </div>
         </div>
      </div>
   </div>
</section>
<!-- Breadcrumb Area End -->


      <section class="peulis-blog-page-area section_70">
         <div class="container">
            <div class="row">
               <div class="col-lg-8">
                  <div class="blog-page-left">
                     <div class="single-blog-item blog-single-page">
                        <div class="blog-image">
                           <img src="{{post.image.url}}" alt="blog" />
                        </div>
                        <div class="blog-desc">
                           <div class="post-meta">
                              <p class="date">20 feb, 2019</p>
                              <p>By <a href="#">Admin</a></p>
                              <p><a href="#">3 comments</a></p>
                           </div>
                           <h3>{{post}}</h3>
                           <p>{{post.content|safe}}</p>
                           <div class="blog-inner-image">
                              <div class="row">
                                 <div class="col-lg-6 col-sm-6">
                                    <div class="destination-desc-img">
                                       {% if post.image %}
                                       <img src="{{post.image1.url}}" alt="gallery 1">
                                        {% endif %}
                                    </div>
                                 </div>
                                 <div class="col-lg-6 col-sm-6">
                                    <div class="destination-desc-img">
                                       <img src="{{post.image2.url}}" alt="gallery 1">
                                    </div>
                                 </div>
                              </div>
                           </div>
                           <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>
                           <div class="destination-desc">
                              <blockquote>
                                 <p>Cillum aute nisi sunt quis duis. Ad anim non velit nulla elit est excepteur proident excepteur laboris. Elit consectetur culpa enim aliquip tempor.</p>
                              </blockquote>
                           </div>
                           <p>Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.</p>
                        </div>
                     </div>
                     <!-- Post Share Box Start -->
                     <div class="post-share-box">
                        <div class="row">
                           <div class="col-lg-6  col-sm-6 no-pad-left">
                              <div class="post-share-left">
                                 <p>
                                    tag :
                                    <a href="#">business ,</a>
                                    <a href="#">finance</a>
                                 </p>
                              </div>
                           </div>
                           <div class="col-lg-6  col-sm-6">
                              <div class="post-share-right">
                                 <p>Share :</p>
                                 <a href="#" class="post_fb">
                                 <i class="fa fa-facebook"></i>
                                 </a>
                                 <a href="#" class="post_twt">
                                 <i class="fa fa-twitter"></i>
                                 </a>
                                 <a href="#" class="post_gl">
                                 <i class="fa fa-google-plus"></i>
                                 </a>
                                 <a href="#" class="post_lknd">
                                 <i class="fa fa-linkedin"></i>
                                 </a>
                              </div>
                           </div>
                        </div>
                     </div>
                     <!-- Post Share Box Start -->

                     <!-- Post Comment Start -->
                     <div class="peulis-comment-list">
                        <div class="comment-group-title">
                           <h3>Comments (03)</h3>
                           <div id="disqus_thread"></div>
                      </div>
                     </div>
                     <!-- Post Comment End -->

                     <!-- Post Comment Form Start -->
                     <div class="peulis-leave-comment">
                        <h3></h3>


                     </div>
                     <!-- Post Comment Form End -->
                  </div>
               </div>
               <div class="col-lg-4">
                  <div class="sidebar-widget">
                     <div class="single-sidebar">
                        <form>
                           <input type="search" placeholder="Search..." />
                           <button type="submit"><i class="fa fa-search"></i></button>
                        </form>
                     </div>
                     <div class="single-sidebar">
                        <h3>Categories</h3>
                        <ul class="category">
                           <li><a href="#">Best Package</a></li>
                           <li><a href="#">Destinations</a></li>
                           <li><a href="#">Discovery</a></li>
                           <li><a href="#">Travel</a></li>
                           <li><a href="#">Trendy</a></li>
                           <li><a href="#">Popular</a></li>
                           <li><a href="#">Events</a></li>
                        </ul>
                     </div>
                     <div class="single-sidebar">
                        <h3>Tags</h3>
                        <ul class="Tags-catagory">
                           <li><a href="#">Fashion</a></li>
                           <li><a href="#">Sea</a></li>
                           <li><a href="#">Mountain</a></li>
                           <li><a href="#">Enjoy</a></li>
                           <li><a href="#">Hot</a></li>
                           <li><a href="#">Popular</a></li>
                           <li><a href="#">Events</a></li>
                        </ul>
                     </div>



                  </div>
               </div>
            </div>
         </div>
      </section>

      <script>
         /**
          *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
          *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables    */

         var disqus_config = function () {
            this.page.url = PAGE_URL = " http://127.0.0.1:8000/{% url 'project:post' post.id %}";
            this.page.identifier = PAGE_IDENTIFIER;
            "{{Post.title}}";
         };

         (function () { // DON'T EDIT BELOW THIS LINE
            var d = document,
               s = d.createElement('script');
            s.src = 'https://secretsof-egypt.disqus.com/embed.js';
            s.setAttribute('data-timestamp', +new Date());
            (d.head || d.body).appendChild(s);
         })();
      </script>
      <noscript> <a href="#">y</a></noscript>

      {% endblock body%}

secretsegypt3-main/Post/templates/edit.html
{% extends "base3.html" %}
{% block body %}
{% load bootstrap4 %}
  <div class="blog_form">
<form method = "post" enctype="multipart/form-data">
  {% csrf_token %}
   {{ form.media }}}
  {% bootstrap_form form %}
    {% buttons %}
        <button type="submit" class="btn btn-primary">Save post</button>
    {% endbuttons %}
</form>
</div>
{% endblock body%}