secretsegypt3-main/Post/urls.py
from django.conf.urls import url
from . import views


app_name = 'Post'


urlpatterns  = [
    url( r'^$' , views.index , name='index'),
    url( 'baset' , views.baset , name='baset'),
    url('all_posts' , views.all_posts , name='all_posts'),
    url(r'^(?P<id>\d+)$', views.post , name='post'),
    url('create',views.create_post, name='create_post'),
    url(r'^(?P<id>\d+)/edit$', views.edit_post ,name='edit_post'),
    url('<slug:slug>/', views.post_detail, name='post_detail')




]

secretsegypt3-main/makeatrip/urls.py
from django.conf.urls import url
from . import views
from django.urls import include, path



app_name = 'makeatrip'

urlpatterns  = [

    path('upload/', views.upload, name='upload'),
    path('books/', views.book_list, name='book_list'),
    path('books/upload/', views.upload_book, name='upload_book'),
    path('books/<int:pk>/', views.delete_book, name='delete_book'),

    path('class/books/', views.BookListView.as_view(), name='class_book_list'),
    path('class/books/upload/', views.UploadBookView.as_view(), name='class_upload_book'),




]

secretsegypt3-main/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),
    path('property', include('property.urls',namespace='property' )),
    path('aswan', include('aswan.urls',namespace='aswan' )),
    path('cairotour', include('cairotour.urls',namespace='cairotour' )),
    path('nilecruise', include('nilecruise.urls',namespace='nilecruise' )),
    path('makeatrip', include('makeatrip.urls',namespace='makeatrip' )),
    path('packages', include('packages.urls',namespace='packages' )),
    path('luxortour', include('luxortour.urls',namespace='luxortour' )),
    path('about', include('about.urls',namespace='about' )),
    path('', include('Post.urls',namespace='project' )),
    path('contact-us/', include('contact.urls',namespace='contact')),
    path('summernote/', include('django_summernote.urls')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_title = "Inspiringegypttours "
admin.site.site_header = "Inspiringegypttours "
admin.site.index_title = "Inspiringegypttours  "
admin.site.accounts = "Inspiringegypttours  "
admin.site.profile = "Inspiringegypttours  "

secretsegypt3-main/templates/base3.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Home Property | Properties Details</title>

    <!-- Favicon -->
    <link rel="shortcut icon" href="img/favicon.ico" type="image/x-icon">

     <!-- Font awesome -->
    <link href="{% static 'css\font-awesome.css'%}"rel="stylesheet">

    <!-- Bootstrap -->
    <link href="{% static 'css\bootstrap.css'%}" rel="stylesheet">
     <!-- slick slider -->
    <link rel="stylesheet" type="text/css" href="{% static 'css\slick.css' %}"/>

   <!-- price picker slider -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/nouislider.css' %}"/>
     <!-- Fancybox slider -->

    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'css/jquery.fancybox.css' %}"/>
     <!-- Theme color -->
    <link id="switcher" rel="stylesheet"  href="{% static 'css/theme-color/default-theme.css' %}"/>
     <!-- Main style sheet -->
   <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" />


     <!-- Google Font -->
     <link href="stylesheet" type="text/css" href="{% static 'https://fonts.googleapis.com/css?family=Vollkorn' %}"/>
     <link href="stylesheet" type="text/css" href="{% static 'https://fonts.googleapis.com/css?family=Open+Sans' %}"/>


    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->


  </head>
  <body class="aa-price-range">
  <!-- Pre Loader -->
  <div id="aa-preloader-area">
    <div class="pulse"></div>
  </div>
  <!-- SCROLL TOP BUTTON -->
    <a class="scrollToTop" href="#"><i class="fa fa-angle-double-up"></i></a>
  <!-- END SCROLL TOP BUTTON -->


  <!-- Start header section -->
  <header id="aa-header">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="aa-header-area">
            <div class="row">
              <div class="col-md-6 col-sm-6 col-xs-6">
                <div class="aa-header-left">
                  <div class="aa-telephone-no">
                    <span class="fa fa-phone"></span>
                    +20 101 794 9933
                  </div>
                  <div class="aa-email hidden-xs">
                    <span class="fa fa-envelope-o"></span> info@tomortravel.com
                  </div>
                </div>
              </div>
              <div class="col-md-6 col-sm-6 col-xs-6">
                <div class="aa-header-right">
                  <a href="register.html" class="aa-register">Register</a>
                  <a href="signin.html" class="aa-login">Login</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>
  <!-- End header section -->
  <!-- Start menu section -->
  <section id="aa-menu-area">
    <nav class="navbar navbar-default main-navbar" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <!-- FOR MOBILE VIEW COLLAPSED BUTTON -->
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <!-- LOGO -->
          <!-- Text based logo -->
          <a class="navbar-brand aa-logo" href="index.html"> Home <span></span></a>
          <!-- Image based logo -->
          <!-- <a class="navbar-brand aa-logo-img" href="index.html"><img src="img/logo.png" alt="logo"></a> -->
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul id="top-menu" class="nav navbar-nav navbar-right aa-main-nav">
            <li class="active"><a href="{% url 'blog:index' %}">HOME</a></li>
             <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="properties.html">DESTINATIONS <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="{% url 'blog:all_posts' %}">LUXOR</a></li>
                <li><a href="#">ASWAN</a></li>
                <li><a href="#l">HURGHADA</a></li>
              </ul>
            </li>
            <li><a href="#">FIGHT BOOKING</a></li>
             <li><a href="#">OMRA&HAJJ</a></li>

             <li><a href="#">NILE CRUISES</a></li>

            </li>
               <li><a href="gallery.html">GALLERY</a></li>
            <li><a href="contact.html">CONTACT</a></li>
                    </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
  </section>
  <!-- End menu section -->

  <!-- Start Proerty header  -->

  <section id="aa-property-header">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="aa-property-header-inner">
            <h2>Tourism details</h2>
            <ol class="breadcrumb">
            <li><a href="#">HOME</a></li>
            <li class="active">{{post}}</li>
          </ol>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- End Proerty header  -->

  <!-- Start Properties  -->
  <section id="aa-properties">
    <div class="container">
      <div class="row">
        <div class="col-md-8">
          <div class="aa-properties-content">
              <!-- Start properties content body -->

                 {% block body %}
                 {% endblock body%}
             <!-- Nearby properties -->

        <!-- Start properties sidebar -->

            <!-- Start Single properties sidebar -->

          </div>
         </div>
       </section>
       <!-- / Properties  -->

       <!-- Footer -->
       <footer id="aa-footer">
         <div class="container">
           <div class="row">
             <div class="col-md-12">
             <div class="aa-footer-area">
               <div class="row">
                 <div class="col-md-3 col-sm-6 col-xs-12">
                   <div class="aa-footer-left">
                    <p>Designed by <a rel="nofollow" href="#">profemahmoud</a></p>
                   </div>
                 </div>
                 <div class="col-md-3 col-sm-6 col-xs-12">
                   <div class="aa-footer-middle">
                     <a href="https://www.facebook.com/pages/category/Travel-Agency/Tomor-travel-1815044958636222/"><i class="fa fa-facebook"></i></a>
                    <a href="https://mail.google.com/mail/?view=cm&fs=1&to= info@tomortravel.com"><i class="fa fa-google-plus"></i></a>
                     <a href="https://api.whatsapp.com/send?phone=00201097247533"><i class="fa fa-whatsapp"></i></a>
                     <a href="#"><i class="fa fa-youtube"></i></a>
                   </div>
                 </div>
                 <div class="col-md-6 col-sm-12 col-xs-12">
                   <div class="aa-footer-right">
                     <a href="#">Home</a>

                   </div>
                 </div>
               </div>
             </div>
           </div>
           </div>
         </div>
       </footer>
       <!-- / Footer -->

         <!-- jQuery library -->
         <!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script> -->

          <script src="{% static 'js/jquery.min.js' %}"></script>

           <!-- Include all compiled plugins (below), or include individual files as needed -->

          <script src="{% static 'js/bootstrap.js' %}"></script>
           <!-- slick slider -->

          <script src="{% static '/js/slick.js' %}" type="text/javascript"></script>

            <!-- Price picker slider -->

          <script src="{% static '/js/nouislider.js' %}" type="text/javascript"></script>
           <!-- mixit slider -->

         <script type="text/javascript" src="{% static "js/jquery.mixitup.js" %}"></script>

           <!-- Add fancyBox -->

         <script src="{% static '/js/jquery.fancybox.pack.js' %}" type="text/javascript"></script>
               <!-- Custom js -->
            <script src="{% static 'js/custom.js' %}"></script>

           </body>
          </html>

secretsegypt3-main/templates/base_generic.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 mx-auto">
                    <div class="apply_job_form white-bg">
                        {% block content %}

                        {% endblock content %}
                    </div>
                </div>
            </div>
        </div>
    </div>


    {% endblock body %}

secretsegypt3-main/templates/book_list.html
{% extends "base.html" %}
{% block content %}

  {% block content_header %}
    <h2>Books</h2>
    <p>
      <a href="{% url 'makeatrip:upload_book' %}" class="btn btn-primary">Upload book</a>
    </p>
  {% endblock %}

  <table class="table mb-0">
    <thead>
      <tr>
        <th>Cover</th>
        <th>Title</th>
        <th>Author</th>
        <th>Download</th>
        <th>Delete</th>
      </tr>
    </thead>
    <tbody>
      {% for book in books %}
        <tr>
          <td>
            {% if makeatrip.cover %}
              <img src="{{ makeatrip.cover.url }}" alt="{{ makeatrip.title }}" style="width:100px;">
            {% else %}
              <span class="text-muted">No cover</span>
            {% endif %}
          </td>
          <td>{{ makeatrip.college }}</td>
          <td>{{ makeatrip.neme }}</td>
          <td>
            <a href="{{ book.pdf.url }}" class="btn btn-primary btn-sm" target="_blank">
              Download PDF
            </a>
          </td>
          <td>
            <form method="post" action="{% url 'accounts:delete_book' book.pk %}">
              {% csrf_token %}
              <button type="submit" class="btn btn-danger btn-sm">Delete</button>
            </form>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

secretsegypt3-main/templates/class_book_list.html
{% extends 'book_list.html' %}

{% block content_header %}
  <h2>Books (Class-Based View)</h2>
  <p>
    <a href="{% url 'class_upload_book' %}" class="btn btn-primary">Upload book</a>
  </p>
{% endblock %}

secretsegypt3-main/templates/upload.html
{% extends 'base.html' %}

{% block content %}
  <h2>Upload</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="myfile">
    <button type="submit">Upload file</button>
  </form>
  {% if url %}
    <p>Uploaded file: <a href="{{ url }}">{{ url }}</a></p>
  {% endif %}
{% endblock %}

secretsegypt3-main/templates/upload_book.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load bootstrap4 %}
{% block body %}

<!-- Breadcrumb Area Start -->
<section class="peulis-breadcrumb-area">
  <div class="breadcrumb-top">
     <div class="container">
        <div class="col-lg-12">
           <div class="breadcrumb-box">
              <h2>makeatrip</h2>
               <ul class="breadcrumb-inn">
                 <li><a href="{% url 'project:index'%}">Home</a></li>
                 <li class="active"><a href="{% url 'project:index'%}">makeatrip</a></li>
               </ul>
           </div>
        </div>
     </div>
  </div>
</section>
<!-- Breadcrumb Area End -->
<!-- Notfound Area Start -->
<section class="peulis-notfound-area section_70">
   <div class="container">
      <div class="row">
         <div class="col-md-12">
           <div class="card">
             <div class="notfound-box">
                 <div class="card-body">
                <h3 class="card-title">makeatrip</h3>
                <form method="post" enctype="multipart/form-data">
                  {% csrf_token %}

                  {% bootstrap_form form %}
                  <br/>
                  <div class="action" style="text-align:center">    <button type="submit"  class="btn btn-success" >Book Now</button> </div>
                </div>
               </div>
           </div>
         </div>
      </div>
   </div>
</section>
<!-- Notfound Area End -->


{% endblock %}